# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .project import *
from .provider import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "gcp-scaffold",
  "mod": "index",
  "fqn": "cobraz_pulumi_gcp_scaffold",
  "classes": {
   "gcp-scaffold:index:project": "Project"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "gcp-scaffold",
  "token": "pulumi:providers:gcp-scaffold",
  "fqn": "cobraz_pulumi_gcp_scaffold",
  "class": "Provider"
 }
]
"""
)
